### ISSUE TITLE
Evaluation time of the model

### ISSUE THREAD

**Issue by chanhee-luke** [valtsblukis/hlsm#3]
Hi, could you share how long it took (with what setup) to evaluate the model on the ALFRED validation splits (mainly validation unseen)? 

Thanks!

**Comment by valtsblukis** [comment]
Hi,
Sorry for the late response. I don't remember the exact amount of time, but it took about a day to collect all the rollouts and complete the evaluation.

**Comment by chanhee-luke** [comment]
Thanks!
